README.md
circle.yml
cumulusci.yml

And configure the repo for 2.0

Convert to using CumulusCI 2.0 for CircleCI builds

---

foo.txt

arbitrary change

---

foo.txt

Putting some Unicode characters in here to make sure we handle them properly.
\u2019: ’
\u2022: •
\u2023: ‣

Pull Request with Unicode characters

---

foo.txt

This branch just makes a change so that we can merge the change to master to test the new parent/child branch functionality in CumulusCI

Test Parent Child branch merging

---

cumulusci.yml

Just that.
Imagine a cute bear here.

Add messy_preflight

---

cumulusci.yml

Assume a spherical cow here, or whatever.
We _think_ that this will work.

[feature/preflight] Add preflight task that will error

---

cumulusci.yml

Add slow-flow

---

cumulusci.yml
tasks/example.py

Work on mock plans for MD testing

---

orgs/beta.json
orgs/dev.json
orgs/feature.json
orgs/release.json

* Replace ``orgPreferences`` with ``orgPreferenceSettings`` in scratch org definition files.

Update scratch org prefs to new format

---

cumulusci.yml
sfdx-project.json
src/applications/CumulusCITest.app
src/quickActions/SampleObject__c.New_Child.quickAction
src/tabs/SampleObject__c.tab

This is partly a test to see what happens to a second PR targeting this branch when I merge this PR and the branch gets autodeleted.

Update API version

---

cumulusci.yml

whitespace

---

foo.txt

* Dev note1
* Dev note2
Informal comment that has many many many many words in it so we can see if this changes things at all. Hopefully this works out great and I don't have to make any more changes in the code because that would be a pain.
* Better text in foo.txt!

Feature/long running  child1

---

foo.txt

* No change notes, just developer notes here.

No change notes, just dev notes

---

foo.txt

Feature/long running  child19

---

foo.txt

Feature/long running1  child1

---

bar.txt

Feature/100  future release check

---

tests/standard_objects/create_contact.robot

Fix a robot test that broke when we updated robot to 4.x

Fix regression with robot 4.x

---

.gitignore
cumulusci.yml

e.g.  https://github.com/SFDO-Tooling/CumulusCI/pull/2866/checks?check_run_id=3589998212#step:12:1
#265 #260

Clean up warnings

---

force-app/main/default/classes/SampleClass2.cls
force-app/main/default/classes/SampleClass2.cls-meta.xml
force-app/main/default/classes/SampleClass2_TEST.cls
force-app/main/default/classes/SampleClass2_TEST.cls-meta.xml

Add a new class with partial code coverage to allow more robust testing of code coverage.﻿

Add uncovered code to test coverage reporting

---

.github/CODEOWNERS

https://salesforce-internal.slack.com/archives/C05DKNXJC15/p1690486398092009

CODEOWNERS Asterisk Fix
